### ISSUE TITLE
收到“#”符号就会回复“指令 # 不存在”的问题

### ISSUE THREAD

**Issue by diyubianfu** [FengLiuFeseliud/pycqBot#23]
不知道消息能不能被看到，我在使用该程序根据b站“伪装人类”的视频建立QQ机器人的时候遇到了如下问题：

简单来说，程序在接收到“#”符号打头的内容就会自动回复“指令 # 不存在”

因为我在一个经常会用这种符号玩角色扮演的跑团群里，所以这个机制非常容易让机器人暴露或刷屏。

我没有较为深刻的计算机知识，在这方面的理解只比常人多那么一点。我翻了视频up提供程序中的好几个py文件，并且询问了ChatGPT，但都没有找到取消这个功能的办法

希望能得到一个解决方式，也希望能见谅一下我可能作为非专业人员的冒昧，也许是我个人的问题，但确实太影响使用了

**Comment by FengLiuFeseliud** [comment]
请自行查看文档 https://fengliufeseliud.github.io/pycqBot/botOptions?id=options-%e9%80%89%e9%a1%b9
