### ISSUE TITLE
找不到

### ISSUE THREAD

**Issue by huaCheng36** [FengLiuFeseliud/pycqBot#24]
from pycqBot.cqApi import cqHttpApi, cqLog
ImportError: cannot import name 'cqHttpApi' from `'pycqBot.cqApi'`
![QQ截图20230511003839](https://github.com/FengLiuFeseliud/pycqBot/assets/77093208/986ed26f-4ab8-4f30-a75a-01910f15982c)
``

**Comment by FengLiuFeseliud** [comment]
先用前一个版本，有点问题

**Comment by huaCheng36** [comment]
前一个版本启动就乱码

**Comment by FengLiuFeseliud** [comment]
说错了, 没问题, 是文档没改, 正确导入
`from pycqBot import cqHttpApi, cqBot, cqLog`

**Comment by FengLiuFeseliud** [comment]
> 前一个版本启动就乱码

说错了, 没问题, 是文档没改, 正确导入
`from pycqBot import cqHttpApi, cqBot, cqLog`
