### ISSUE TITLE
pip install pycqBot后找不到对应的import

### ISSUE THREAD

**Issue by Tempestissimo616** [FengLiuFeseliud/pycqBot#25]
我找到一个b站up主弄的qq机器人的代码，其中
from pycqBot.cqApi import cqHttpApi, cqLog   #这个
from pycqBot import Message, cqCode             #这个
import pandas as pd
import random
import logging
import chat
import time
import json
from datetime import datetime
import re
import os

在我安装pycqBot后找不到，'cqHttpApi' from 'pycqBot.cqApi'和message
Traceback (most recent call last):
  File "E:\qqBotPlus\Spit_chatBot\qqbot.py", line 11, in <module>
    from pycqBot.cqApi import cqHttpApi, cqLog
ImportError: cannot import name 'cqHttpApi' from 'pycqBot.cqApi' (D:\python3.11\Lib\site-packages\pycqBot\cqApi.py)
ImportError: cannot import name 'Message' from 'pycqBot' (D:\python3.11\Lib\site-packages\pycqBot\__init__.py)
版本是
PS E:\qqBotPlus\Spit_chatBot> pip show pycqBot
Name: pycqBot
Version: 0.5.1.1
Summary: go-cqhttp python 框架，可以用于快速塔建 bot
Home-page: https://github.com/FengLiuFeseliud/pycqBot
Author: FengLiuFeseliud
Author-email: 17351198406@qq.com
License: AGPL-3.0 License
Location: D:\python3.11\Lib\site-packages
Requires: aiofiles, aiohttp, asyncio, lxml, pyyaml, requests, websockets
Required-by:
PS E:\qqBotPlus\Spit_chatBot>这个跟python版本有问题吗？因为作者是用的3.9做的机器人

**Comment by FengLiuFeseliud** [comment]
改用导入
`from pycqBot import cqHttpApi, cqBot, cqLog`

**Comment by Tempestissimo616** [comment]
好的，但是还有另外一个import的问题，ImportError: cannot import name 'Message' from 'pycqBot' (D:\python3.11\Lib\site-packages\pycqBot\__init__.py)  
from pycqBot import Message, cqCode
我找不到Message

**Comment by zcy8557** [comment]
我也是这个问题

**Comment by FengLiuFeseliud** [comment]
> 好的，但是还有另外一个import的问题，ImportError: cannot import name 'Message' from 'pycqBot' (D:\python3.11\Lib\site-packages\pycqBot__init__.py) from pycqBot import Message, cqCode 我找不到Message

这个都有写了 from pycqBot.data import *

**Comment by Tempestissimo616** [comment]
> 我也是这个问题

你弄好了吗

**Comment by Tempestissimo616** [comment]
我已经解决了，谢谢作者了。必须要版本pycqbot==0.4.5.1
