### ISSUE TITLE
帮助文档内“help的使用”处标点错误

### ISSUE THREAD

**Issue by LuoTianOrange** [FengLiuFeseliud/pycqBot#32]
https://fengliufeseliud.github.io/pycqBot/botOptions

`bot.command(echo, "echo"， {
    # 指令帮助信息
    "help": [
        "#echo - 输出文本",
        "   这个指令没有参数~",
        "   这个指令所有用户可用~",
    ]
})
`
第二个echo后使用了中文的逗号

**Comment by SydrrO** [comment]
您好，我是这个脚本的使用者之一，我最近遇到了一些问题，但是他本人一直不回复，我想问问您，如何获取群成员的信息，比我我问他1还是2，我如何将他的回答返回后台呢，谢谢
