### ISSUE TITLE
'.\go-cqhttp.exe' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by Carofield** [FengLiuFeseliud/pycqBot#7]
bot.start() 后出现下述问题：

[2023-02-05 05:37:22,226][MainThread/DEBUG] PyCqBot: Using proactor: IocpProactor

#################################################################
██████╗ ██╗   ██╗ ██████╗ ██████╗ ██████╗  ██████╗ ████████╗
██╔══██╗╚██╗ ██╔╝██╔════╝██╔═══██╗██╔══██╗██╔═══██╗╚══██╔══╝
██████╔╝ ╚████╔╝ ██║     ██║   ██║██████╔╝██║   ██║   ██║   
██╔═══╝   ╚██╔╝  ██║     ██║▄▄ ██║██╔══██╗██║   ██║   ██║   
██║        ██║   ╚██████╗╚██████╔╝██████╔╝╚██████╔╝   ██║   
╚═╝        ╚═╝    ╚═════╝ ╚══▀▀═╝ ╚═════╝  ╚═════╝    ╚═╝   
                                            v0.4.5  BY FengLiu
#################################################################

'.\go-cqhttp.exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by XMZOVO** [comment]
`bot.start("go-cqhttp.exe所在相对路径")`
